/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Interface.java
 *
 * Created on 4 déc. 2012, 17:12:44
 */

/**
 *
 * @author scoavoux
 */
public class Interface extends javax.swing.JFrame {

    /** Creates new form Interface */
    public Interface() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        ajoutAmi = new javax.swing.JFrame();
        ouiOui = new javax.swing.JButton();
        ouiNon = new javax.swing.JButton();
        nonNon = new javax.swing.JButton();
        demande = new javax.swing.JLabel();
        statut = new javax.swing.JTextField();
        post = new javax.swing.JButton();
        listFriends = new javax.swing.JLabel();
        pub = new javax.swing.JRadioButton();
        priv = new javax.swing.JRadioButton();
        myPosts = new javax.swing.JLabel();
        theirPosts = new javax.swing.JLabel();
        addFriends = new javax.swing.JTextField();
        add = new javax.swing.JButton();
        me = new javax.swing.JPanel();
        them = new javax.swing.JPanel();
        myFriends = new javax.swing.JPanel();

        ouiOui.setText("Oui, l'ajouter en retour");

        ouiNon.setText("Oui, mais ne pas l'ajouter");

        nonNon.setText("Non, je ne veux pas qu'il/elle lise mes statuts public");

        demande.setText("Machin vous a ajouté comme ami(e). Voulez-vous?");

        javax.swing.GroupLayout ajoutAmiLayout = new javax.swing.GroupLayout(ajoutAmi.getContentPane());
        ajoutAmi.getContentPane().setLayout(ajoutAmiLayout);
        ajoutAmiLayout.setHorizontalGroup(
            ajoutAmiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ajoutAmiLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ajoutAmiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ajoutAmiLayout.createSequentialGroup()
                        .addGroup(ajoutAmiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nonNon, javax.swing.GroupLayout.DEFAULT_SIZE, 376, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ajoutAmiLayout.createSequentialGroup()
                                .addComponent(ouiOui)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ouiNon)))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ajoutAmiLayout.createSequentialGroup()
                        .addComponent(demande)
                        .addGap(37, 37, 37))))
        );
        ajoutAmiLayout.setVerticalGroup(
            ajoutAmiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ajoutAmiLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(demande, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(ajoutAmiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ouiOui)
                    .addComponent(ouiNon))
                .addGap(18, 18, 18)
                .addComponent(nonNon)
                .addGap(20, 20, 20))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        post.setText("Publier");

        listFriends.setText("Liste d'amis");

        pub.setText("Public");

        priv.setText("Privé");

        myPosts.setText("Moi");

        theirPosts.setText("Vous");

        addFriends.setText("Nom d'utilisateur");

        add.setText("Ajouter");

        javax.swing.GroupLayout meLayout = new javax.swing.GroupLayout(me);
        me.setLayout(meLayout);
        meLayout.setHorizontalGroup(
            meLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 271, Short.MAX_VALUE)
        );
        meLayout.setVerticalGroup(
            meLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 482, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout themLayout = new javax.swing.GroupLayout(them);
        them.setLayout(themLayout);
        themLayout.setHorizontalGroup(
            themLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 267, Short.MAX_VALUE)
        );
        themLayout.setVerticalGroup(
            themLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 474, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout myFriendsLayout = new javax.swing.GroupLayout(myFriends);
        myFriends.setLayout(myFriendsLayout);
        myFriendsLayout.setHorizontalGroup(
            myFriendsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 225, Short.MAX_VALUE)
        );
        myFriendsLayout.setVerticalGroup(
            myFriendsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 384, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(statut, javax.swing.GroupLayout.DEFAULT_SIZE, 564, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addComponent(myPosts, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(134, 134, 134)
                        .addComponent(theirPosts, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(108, 108, 108))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(me, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(17, 17, 17)
                        .addComponent(them, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addComponent(add))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(priv)
                            .addComponent(pub))
                        .addGap(32, 32, 32)
                        .addComponent(post, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(13, 13, 13))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(addFriends, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26))
                    .addComponent(listFriends, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(myFriends, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(statut, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(post, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(pub)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(priv)))
                        .addGap(8, 8, 8)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(myPosts)
                    .addComponent(theirPosts))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(addFriends, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(add)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(listFriends, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(myFriends, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(them, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(me, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(83, 83, 83))
        );
        
        buttonGroup1.add(pub);
        buttonGroup1.add(priv);
        pub.setSelected(true);

        pack();
    }// </editor-fold>

    /**
    * @param args the command line arguments
    */


    // Variables declaration - do not modify
    public javax.swing.JButton add;
    public javax.swing.JTextField addFriends;
    public javax.swing.JFrame ajoutAmi;
    public javax.swing.ButtonGroup buttonGroup1;
    public javax.swing.JLabel demande;
    public javax.swing.JLabel listFriends;
    public javax.swing.JPanel me;
    public javax.swing.JPanel myFriends;
    public javax.swing.JLabel myPosts;
    public javax.swing.JButton nonNon;
    public javax.swing.JButton ouiNon;
    public javax.swing.JButton ouiOui;
    public javax.swing.JButton post;
    public javax.swing.JRadioButton priv;
    public javax.swing.JRadioButton pub;
    public javax.swing.JTextField statut;
    public javax.swing.JLabel theirPosts;
    public javax.swing.JPanel them;
    // End of variables declaration

}
