/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Interface.java
 *
 * Created on 21 déc. 2012, 17:50:32
 */



/**
 *
 * @author ysenel
 */
public class Interface extends javax.swing.JFrame {

    /** Creates new form Interface */
    public Interface() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        demandeAmi = new javax.swing.JFrame();
        ouiOui = new javax.swing.JButton();
        ouiNon = new javax.swing.JButton();
        nonNon = new javax.swing.JButton();
        demande = new javax.swing.JLabel();
        connect = new javax.swing.JFrame();
        connecter = new javax.swing.JLabel();
        ok = new javax.swing.JButton();
        status = new javax.swing.JTextField();
        pub = new javax.swing.JRadioButton();
        priv = new javax.swing.JRadioButton();
        post = new javax.swing.JButton();
        myPosts = new javax.swing.JLabel();
        theirPosts = new javax.swing.JLabel();
        me = new javax.swing.JPanel();
        them = new javax.swing.JPanel();
        addFriends = new javax.swing.JTextField();
        add = new javax.swing.JButton();
        suppr = new javax.swing.JButton();
        myFriends = new javax.swing.JPanel();
        listFriends = new javax.swing.JLabel();

        ouiOui.setText("Oui, l'ajouter en retour");

        ouiNon.setText("Oui, mais ne pas l'ajouter");

        nonNon.setText("Non, je ne veux pas qu(il/elle lise mes status public");

        demande.setText("ysenel vous a ajouté comme ami(e). Voulez-vous?");

        javax.swing.GroupLayout demandeAmiLayout = new javax.swing.GroupLayout(demandeAmi.getContentPane());
        demandeAmi.getContentPane().setLayout(demandeAmiLayout);
        demandeAmiLayout.setHorizontalGroup(
            demandeAmiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(demandeAmiLayout.createSequentialGroup()
                .addGroup(demandeAmiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(demandeAmiLayout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(demande, javax.swing.GroupLayout.PREFERRED_SIZE, 354, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(demandeAmiLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(ouiOui, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(ouiNon, javax.swing.GroupLayout.DEFAULT_SIZE, 199, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, demandeAmiLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(nonNon, javax.swing.GroupLayout.DEFAULT_SIZE, 389, Short.MAX_VALUE)))
                .addContainerGap())
        );
        demandeAmiLayout.setVerticalGroup(
            demandeAmiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(demandeAmiLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(demande, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(demandeAmiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ouiOui)
                    .addComponent(ouiNon))
                .addGap(18, 18, 18)
                .addComponent(nonNon)
                .addContainerGap(33, Short.MAX_VALUE))
        );

        connecter.setText("toto est connecté");

        ok.setText("OK");

        javax.swing.GroupLayout connectLayout = new javax.swing.GroupLayout(connect.getContentPane());
        connect.getContentPane().setLayout(connectLayout);
        connectLayout.setHorizontalGroup(
            connectLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(connectLayout.createSequentialGroup()
                .addGap(115, 115, 115)
                .addGroup(connectLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(ok, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(connecter, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 117, Short.MAX_VALUE))
                .addContainerGap(141, Short.MAX_VALUE))
        );
        connectLayout.setVerticalGroup(
            connectLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(connectLayout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(connecter)
                .addGap(18, 18, 18)
                .addComponent(ok)
                .addContainerGap(93, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pub.setText("Public");

        priv.setText("Privé");

        post.setText("Publier");

        myPosts.setText("Moi");

        theirPosts.setText("Vous");

        javax.swing.GroupLayout meLayout = new javax.swing.GroupLayout(me);
        me.setLayout(meLayout);
        meLayout.setHorizontalGroup(
            meLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 242, Short.MAX_VALUE)
        );
        meLayout.setVerticalGroup(
            meLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 399, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout themLayout = new javax.swing.GroupLayout(them);
        them.setLayout(themLayout);
        themLayout.setHorizontalGroup(
            themLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 258, Short.MAX_VALUE)
        );
        themLayout.setVerticalGroup(
            themLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 399, Short.MAX_VALUE)
        );

        addFriends.setText("Nom d'utilisateur");

        add.setText("Ajouter");

        suppr.setText("Supprimer");

        javax.swing.GroupLayout myFriendsLayout = new javax.swing.GroupLayout(myFriends);
        myFriends.setLayout(myFriendsLayout);
        myFriendsLayout.setHorizontalGroup(
            myFriendsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 151, Short.MAX_VALUE)
        );
        myFriendsLayout.setVerticalGroup(
            myFriendsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 276, Short.MAX_VALUE)
        );

        listFriends.setText("Liste d'amis");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(status, javax.swing.GroupLayout.PREFERRED_SIZE, 406, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(pub)
                            .addComponent(priv))
                        .addGap(38, 38, 38)
                        .addComponent(post, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(myPosts)
                        .addGap(236, 236, 236)
                        .addComponent(theirPosts))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(me, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(them, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(listFriends)
                            .addComponent(myFriends, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(addFriends)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(suppr)
                                    .addComponent(add, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(17, 17, 17)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(post, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(status, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(pub)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(priv)))
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(myPosts)
                    .addComponent(theirPosts))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(them, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(me, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(addFriends, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(add)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(suppr)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(listFriends)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                        .addComponent(myFriends, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        buttonGroup1.add(pub);
        buttonGroup1.add(priv);
        pub.setSelected(true);

        pack();
    }// </editor-fold>

    /**
    * @param args the command line arguments
    */


    // Variables declaration - do not modify
    public javax.swing.JButton add;
    public javax.swing.JTextField addFriends;
    public javax.swing.ButtonGroup buttonGroup1;
    public javax.swing.JFrame connect;
    public javax.swing.JLabel connecter;
    public javax.swing.JLabel demande;
    public javax.swing.JFrame demandeAmi;
    public javax.swing.JLabel listFriends;
    public javax.swing.JPanel me;
    public javax.swing.JPanel myFriends;
    public javax.swing.JLabel myPosts;
    public javax.swing.JButton nonNon;
    public javax.swing.JButton ok;
    public javax.swing.JButton ouiNon;
    public javax.swing.JButton ouiOui;
    public javax.swing.JButton post;
    public javax.swing.JRadioButton priv;
    public javax.swing.JRadioButton pub;
    public javax.swing.JTextField status;
    public javax.swing.JButton suppr;
    public javax.swing.JLabel theirPosts;
    public javax.swing.JPanel them;
    // End of variables declaration

}
